excluded:
  - Pods
disabled_rules:
  - identifier_name
  - nesting
  - function_parameter_count
  - trailing_whitespace

opt_in_rules:
  - control_statement
  - empty_count
  - first_where
  - redundant_nil_coalescing
  - switch_case_on_newline
  - closure_spacing
  - empty_string
  - toggle_bool
  - strict_fileprivate
  - static_operator
  - sorted_first_last
  - redundant_type_annotation
  - private_outlet
  - private_action
  - no_extension_access_modifier
  
analyzer_rules:
  - unused_declaration
  - unused_import
  - explicit_self

line_length: 350

type_body_length:
  warning: 300
  error: 400
  
function_body_length:
  warning: 90
  error: 100

large_tuple:
  warning: 3
  error: 4

file_length:
  warning: 500
  error: 800

identifier_name:
  min_length: 3
type_name:
  min_length: 3
  
force_cast: warning
force_try: warning
